### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 621904204 for 6f67d41bbd1e193456c04c0bed7b0c2930552336

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/621904204

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 621912883 for 3dfba140d3b2e5865e90e0f71eaffb4d362ba4a4

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/621912883

**Comment by CMCDragonkai** [comment]
@tegefaulkes will be released as 1.0.0.

**Comment by CMCDragonkai** [comment]
We can try this out and see how this can be applied to async generators later which does have slightly different issues with the syntax. One is the ability to cancel the promises themselves, another is to interrupt the generator between its yield. Both have different semantics. Will need to see in field to see how it works.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 621918269 for 52f474834654122055f6fb26a4f691516114a544

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/621918269

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 621912883 for 3dfba140d3b2e5865e90e0f71eaffb4d362ba4a4

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/621912883

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 621918269 for 52f474834654122055f6fb26a4f691516114a544

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/621918269

**Pull request merged**
