### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 715233275 for 16de2a653c80d936e2cbd8fde7a07f5522df1fee

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/715233275

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 715304063 for 16de2a653c80d936e2cbd8fde7a07f5522df1fee

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/715304063

**Comment by CMCDragonkai** [comment]
@tegefaulkes there's a failure here in:

```
  ● PromiseCancellable › PromiseCancellable.from › from a cancellable function with default early rejection
    expect(received).rejects.toBeUndefined()
    Received: {}
      160 |       const pC = PromiseCancellable.from(p);
      161 |       pC.cancel();
    > 162 |       await expect(pC).rejects.toBeUndefined();
          |                                ^
      163 |       await expect(p).resolves.toBe('Result');
      164 |     });
      165 |   });
      at Object.toBeUndefined (node_modules/expect/build/index.js:241:22)
      at Object.<anonymous> (tests/PromiseCancellable.test.ts:162:32)
```

But only affects the mac builder.

This same error affects `js-timer` in https://github.com/MatrixAI/js-timer/pull/4

Can you check if this is a regression next. I'll label this as a bug.

**Comment by CMCDragonkai** [comment]
We tested this on the matrix-mac-1, no problems there. It's only the Mac CI/CD. @tegefaulkes is looking into this in the CI/CD by pushing a bunch of `console.log` traces.

**Comment by CMCDragonkai** [comment]
If fixed, then new update for this, and have to propagate that update across the rest of the downstream repos like `js-timer` which also has its CI/CD blocked on this bug.

**Comment by CMCDragonkai** [comment]
Ultimately we want to know on the Mac CI/CD why `await pC` rejection is just `{}` when we are expecting `undefined` and it is `undefined` for all other platforms.

```js
try {
  await pC;
} catch (e) {
  console.log(typeof e);
  console.log(e);
  console.log(e.name);
  console.dir(e);
}
```

You may then trace backwards to look at where the `reject` call is being made inside `PromiseCancellable`, and where that object is coming from.

**Comment by tegefaulkes** [comment]
I've found the problem. It seems that aborting the `AbortController` with `abortController.abort()` or `abortController.abort(undefined)` results in the `abortController.signal.reason` to be a `DOMException [AbortError]: This operation was aborted` error. It seems that the controller is helpfully filling in the reason for us if one is not provided but ONLY in the macos CI job. 

The fix I'm going with here is to use an internal symbol `symbolUndefinedReason` in place of undefined for the abort reason. When receiving the abort event and rejecting we convert this back to undefined. This should be portable.

**Comment by CMCDragonkai** [comment]
I prefer you calling it `cancelXReason` where `X` can be something. This names it similar to our tasks domain in PK. Could be `cancelDefaultReason` or `cancelUndefinedReason`.

**Comment by CMCDragonkai** [comment]
The macos had a later version of node where `AbortError` exists, technically it was doing the **correct** thing while all our other platforms were not. See https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

Other current nodejs doesn't, so by doing the above, everything will behave the same. It does mean `pC.cancel()` and `pC.cancel(undefined)` will reject with `undefined`.

Note:

```
      await expect(Promise.reject(undefined)).rejects.toBe(undefined);
      await expect(Promise.reject(new Error)).rejects.toThrow(undefined);
```

**Comment by CMCDragonkai** [comment]
@tegefaulkes please update and release a patch version after staging merges. Then propagate updates to all users of `async-cancellable`. I think `js-timers` and `Polykey`.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 806740243 for 0dbf46c0ae3e887649b09af6caee85dbdd1966fa

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/806740243

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 806740243 for 0dbf46c0ae3e887649b09af6caee85dbdd1966fa

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/806740243

**Comment by tegefaulkes** [comment]
> The macos had a later version of node where `AbortError` exists. Other current nodejs doesn't so, by doing the above, everything will behave the same. It does mean `pC.cancel()` and `pC.cancel(undefined)` will reject with `undefined`.
> 
> Note:
> 
> ```
>       await expect(Promise.reject(undefined)).rejects.toBe(undefined);
>       await expect(Promise.reject(new Error)).rejects.toThrow(undefined);
> ```

Yes, both `cancel()` and `cancel(undefined)` will cause the promise to reject with `undefined`.

With this merged now I'll push a patch version and update any dependants.

**Pull request merged**
