### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 881527139 for 0e4280055ee2453d78390f720625b7b4473f9000

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/881527139

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 881527234 for 49e8c11ee62d7bea615d2c5f47d521223a8af32c

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/881527234

**Comment by ghost** [comment]
<details open>
<summary><b>👇 <a href="https://app.codesee.io/r/reviews?pr=14&src=https%3A%2F%2Fgithub.com%2FMatrixAI%2Fjs-async-cancellable">Click on the image</a> for a new way to code review</b>
</summary>

####

[Review these changes using an interactive CodeSee Map](https://app.codesee.io/r/reviews?pr=14&src=https%3A%2F%2Fgithub.com%2FMatrixAI%2Fjs-async-cancellable)

#### Legend
CodeSee Map legend
</details>

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 881527139 for 0e4280055ee2453d78390f720625b7b4473f9000

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/881527139

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 881527234 for 49e8c11ee62d7bea615d2c5f47d521223a8af32c

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/881527234

**Pull request merged**
