### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 891092358 for 809fd0b61011f37c9c27997ca97975c31bab24ea

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/891092358

**Comment by ghost** [comment]
<details open>
<summary><b>👇 <a href="https://app.codesee.io/r/reviews?pr=15&src=https%3A%2F%2Fgithub.com%2FMatrixAI%2Fjs-async-cancellable">Click on the image</a> for a new way to code review</b>
</summary>

####

[Review these changes using an interactive CodeSee Map](https://app.codesee.io/r/reviews?pr=15&src=https%3A%2F%2Fgithub.com%2FMatrixAI%2Fjs-async-cancellable)

#### Legend
CodeSee Map legend
</details>

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 891117658 for 30f8644fcb66e50a6e5a9d20b1c4fce7475df35e

https://gitlab.com/MatrixAI/open-source/js-async-cancellable/-/pipelines/891117658

**Comment by CMCDragonkai** [comment]
Going to merge this myself since macos runners are disabled atm.

**Pull request merged**
